% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\title{Assignment3}
\author{Swetha}
\date{3/1/2022}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Assignment3},
  pdfauthor={Swetha},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\begin{document}
\maketitle

loading all packages

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(caret)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: ggplot2
\end{verbatim}

\begin{verbatim}
## Loading required package: lattice
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(lattice)}
\FunctionTok{library}\NormalTok{(knitr)}
\FunctionTok{library}\NormalTok{(rmarkdown)}
\FunctionTok{library}\NormalTok{(e1071)}
\end{Highlighting}
\end{Shaded}

Now I'll load the UniversalBank.csv file . Here I am calling csv and
factor variables

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{getwd}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "C:/Users/mercy/OneDrive/Desktop/FML/Assignment3"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{setwd}\NormalTok{(}\StringTok{"C:/Users/mercy/OneDrive/Desktop/FML/Assignment3"}\NormalTok{)}
\NormalTok{Original }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"UniversalBank.csv"}\NormalTok{)}
\NormalTok{DF\_Universal\_Bank }\OtherTok{\textless{}{-}}\NormalTok{ Original }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(Age, Experience, Income, Family, CCAvg, Education, Mortgage, Personal.Loan, Securities.Account, CD.Account, Online, CreditCard)}
\NormalTok{DF\_Universal\_Bank}\SpecialCharTok{$}\NormalTok{CreditCard }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(DF\_Universal\_Bank}\SpecialCharTok{$}\NormalTok{CreditCard)}
\NormalTok{DF\_Universal\_Bank}\SpecialCharTok{$}\NormalTok{Personal.Loan }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{((DF\_Universal\_Bank}\SpecialCharTok{$}\NormalTok{Personal.Loan))}
\NormalTok{DF\_Universal\_Bank}\SpecialCharTok{$}\NormalTok{Online }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(DF\_Universal\_Bank}\SpecialCharTok{$}\NormalTok{Online)}
\end{Highlighting}
\end{Shaded}

Removing ID and ZipCode \#\#Create Partition

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{selected.var }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{8}\NormalTok{,}\DecValTok{11}\NormalTok{,}\DecValTok{12}\NormalTok{)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{23}\NormalTok{)}
\NormalTok{Train\_Index }\OtherTok{=} \FunctionTok{createDataPartition}\NormalTok{(DF\_Universal\_Bank}\SpecialCharTok{$}\NormalTok{Personal.Loan, }\AttributeTok{p=}\FloatTok{0.60}\NormalTok{, }\AttributeTok{list=}\ConstantTok{FALSE}\NormalTok{)}
\NormalTok{Train\_Data }\OtherTok{=}\NormalTok{ DF\_Universal\_Bank[Train\_Index,selected.var]}
\NormalTok{Validation\_Data }\OtherTok{=}\NormalTok{ DF\_Universal\_Bank[}\SpecialCharTok{{-}}\NormalTok{Train\_Index,selected.var]}
\end{Highlighting}
\end{Shaded}

Then it creates the data partition, train data and validation data \#\#A

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{attach}\NormalTok{(Train\_Data)}
\FunctionTok{ftable}\NormalTok{(CreditCard,Personal.Loan,Online)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                          Online    0    1
## CreditCard Personal.Loan                 
## 0          0                     773 1127
##            1                      82  114
## 1          0                     315  497
##            1                      39   53
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{detach}\NormalTok{(Train\_Data)}
\end{Highlighting}
\end{Shaded}

The pivot table is now created with online as a column and CC and LOAN
as rows.

\begin{enumerate}
\def\labelenumi{\Alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  (probability not using Naive Bayes) With Online=1 and CC=1, we can
  calculate the likelihood that Loan=1 by , we add 53(Loan=1 from
  ftable) and 497(Loan=0 from ftable) which gives us 550. So the
  probability is 53/(53+497) =53/550 = 0.096363 or 9.64\% . Hence the
  probability is 9.64\%
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{prop.table}\NormalTok{(}\FunctionTok{ftable}\NormalTok{(Train\_Data}\SpecialCharTok{$}\NormalTok{CreditCard,Train\_Data}\SpecialCharTok{$}\NormalTok{Online,Train\_Data}\SpecialCharTok{$}\NormalTok{Personal.Loan),}\AttributeTok{margin=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               0          1
##                           
## 0 0  0.90409357 0.09590643
##   1  0.90813860 0.09186140
## 1 0  0.88983051 0.11016949
##   1  0.90363636 0.09636364
\end{verbatim}

The code above gives a proportion pivot table that can assist in
answering question B.This table shows the chances of getting a loan if
you have a credit card and you apply online. \#\#C)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{attach}\NormalTok{(Train\_Data)}
\FunctionTok{ftable}\NormalTok{(Personal.Loan,Online)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               Online    0    1
## Personal.Loan                 
## 0                    1088 1624
## 1                     121  167
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ftable}\NormalTok{(Personal.Loan,CreditCard)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               CreditCard    0    1
## Personal.Loan                     
## 0                        1900  812
## 1                         196   92
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{detach}\NormalTok{(Train\_Data)}
\end{Highlighting}
\end{Shaded}

The two pivot tables necessary for C are returned above. The first is a
column with Online as a column and Loans as a row, while the second is a
column with Credit Card as a column. \#\#D

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{prop.table}\NormalTok{(}\FunctionTok{ftable}\NormalTok{(Train\_Data}\SpecialCharTok{$}\NormalTok{Personal.Loan,Train\_Data}\SpecialCharTok{$}\NormalTok{CreditCard),}\AttributeTok{margin=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            0         1
##                       
## 0  0.7005900 0.2994100
## 1  0.6805556 0.3194444
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{prop.table}\NormalTok{(}\FunctionTok{ftable}\NormalTok{(Train\_Data}\SpecialCharTok{$}\NormalTok{Personal.Loan,Train\_Data}\SpecialCharTok{$}\NormalTok{Online),}\AttributeTok{margin=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            0         1
##                       
## 0  0.4011799 0.5988201
## 1  0.4201389 0.5798611
\end{verbatim}

The code above displays a proportion pivot table that can assist in
answering question D. Di) 92/288 = 0.3194 or 31.94\%

Dii) 167/288 = 0.5798 or 57.986\%

Diii) total loans= 1 from table (288) is now divided by total count from
table (3000) = 0.096 or 9.6\%

DiV) 812/2712 = 0.2994 or 29.94\%

\begin{enumerate}
\def\labelenumi{\Roman{enumi})}
\setcounter{enumi}{504}
\tightlist
\item
  1624/2712 = 0.5988 or 59.88\%
\end{enumerate}

DVi) total loans=0 from table(2712) which is divided by total count from
table (3000) = 0.904 or 90.4\%

\#\#E)Naive Bayes calculation (0.3194 * 0.5798 * 0.096)/{[}(0.3194 *
0.5798 * 0.096)+(0.2994 * 0.5988 * 0.904){]} = 0.0988505642823701 or
9.885\%

\#\#F) B employs a direct computation based on a count, whereas E
employs probability for each of the counts. As a result, whereas E is
ideal for broad generality, B is more precise.

\#\#G)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Universal.nb }\OtherTok{\textless{}{-}} \FunctionTok{naiveBayes}\NormalTok{(Personal.Loan }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ Train\_Data)}
\NormalTok{Universal.nb}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Naive Bayes Classifier for Discrete Predictors
## 
## Call:
## naiveBayes.default(x = X, y = Y, laplace = laplace)
## 
## A-priori probabilities:
## Y
##     0     1 
## 0.904 0.096 
## 
## Conditional probabilities:
##    Online
## Y           0         1
##   0 0.4011799 0.5988201
##   1 0.4201389 0.5798611
## 
##    CreditCard
## Y           0         1
##   0 0.7005900 0.2994100
##   1 0.6805556 0.3194444
\end{verbatim}

While utilizing the two tables created in step C makes it easy to see
how you're computing P(LOAN=1\textbar CC=1,Online=1) using the Naive
Bayes model, you can also use the pivot table built in step B to rapidly
compute P(LOAN=1\textbar CC=1,Online=1) without using the Naive Bayes
model. The Naive Bayes model predicts the same probability as the
previous techniques, although it is lower than the probability
calculated by hand in step E. This probability is closer to the one
calculated in step B. This could be due to the fact that we are doing
the calculations by hand in step E, which leaves space for mistake when
rounding fractions, resulting in simply an approximation. \#\# NB
confusion matrix for Train\_Data

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pred.class }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(Universal.nb, }\AttributeTok{newdata =}\NormalTok{ Train\_Data)}
\FunctionTok{confusionMatrix}\NormalTok{(pred.class, Train\_Data}\SpecialCharTok{$}\NormalTok{Personal.Loan)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    0    1
##          0 2712  288
##          1    0    0
##                                           
##                Accuracy : 0.904           
##                  95% CI : (0.8929, 0.9143)
##     No Information Rate : 0.904           
##     P-Value [Acc > NIR] : 0.5157          
##                                           
##                   Kappa : 0               
##                                           
##  Mcnemar's Test P-Value : <2e-16          
##                                           
##             Sensitivity : 1.000           
##             Specificity : 0.000           
##          Pos Pred Value : 0.904           
##          Neg Pred Value :   NaN           
##              Prevalence : 0.904           
##          Detection Rate : 0.904           
##    Detection Prevalence : 1.000           
##       Balanced Accuracy : 0.500           
##                                           
##        'Positive' Class : 0               
## 
\end{verbatim}

This model exhibited a low specificity despite being super sensitive.
The model anticipated that all values would be zero, but the reference
had all true values. Despite missing all 1 data, the model still returns
a 90.4 percent accuracy due to the enormous number of 0 values.
\#\#Validation set

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pred.prob }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(Universal.nb, }\AttributeTok{newdata=}\NormalTok{Validation\_Data, }\AttributeTok{type=}\StringTok{"raw"}\NormalTok{)}
\NormalTok{pred.class }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(Universal.nb, }\AttributeTok{newdata =}\NormalTok{ Validation\_Data)}
\FunctionTok{confusionMatrix}\NormalTok{(pred.class, Validation\_Data}\SpecialCharTok{$}\NormalTok{Personal.Loan)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    0    1
##          0 1808  192
##          1    0    0
##                                           
##                Accuracy : 0.904           
##                  95% CI : (0.8902, 0.9166)
##     No Information Rate : 0.904           
##     P-Value [Acc > NIR] : 0.5192          
##                                           
##                   Kappa : 0               
##                                           
##  Mcnemar's Test P-Value : <2e-16          
##                                           
##             Sensitivity : 1.000           
##             Specificity : 0.000           
##          Pos Pred Value : 0.904           
##          Neg Pred Value :   NaN           
##              Prevalence : 0.904           
##          Detection Rate : 0.904           
##    Detection Prevalence : 1.000           
##       Balanced Accuracy : 0.500           
##                                           
##        'Positive' Class : 0               
## 
\end{verbatim}

Let's look at the model graphically and see what the best threshold is
for it.

\#\#ROC

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(pROC)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Type 'citation("pROC")' for a citation.
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'pROC'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     cov, smooth, var
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{roc}\NormalTok{(Validation\_Data}\SpecialCharTok{$}\NormalTok{Personal.Loan,pred.prob[,}\DecValTok{1}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Setting levels: control = 0, case = 1
\end{verbatim}

\begin{verbatim}
## Setting direction: controls < cases
\end{verbatim}

\begin{verbatim}
## 
## Call:
## roc.default(response = Validation_Data$Personal.Loan, predictor = pred.prob[,     1])
## 
## Data: pred.prob[, 1] in 1808 controls (Validation_Data$Personal.Loan 0) < 192 cases (Validation_Data$Personal.Loan 1).
## Area under the curve: 0.5302
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot.roc}\NormalTok{(Validation\_Data}\SpecialCharTok{$}\NormalTok{Personal.Loan,pred.prob[,}\DecValTok{1}\NormalTok{],}\AttributeTok{print.thres=}\StringTok{"best"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Setting levels: control = 0, case = 1
## Setting direction: controls < cases
\end{verbatim}

\includegraphics{Assignment3_files/figure-latex/unnamed-chunk-11-1.pdf}

This shows that setting a threshold of 0.906 could improve the model by
lowering sensitivity to 0.495 and increasing specificity to 0.576. ```

\end{document}
